### ISSUE TITLE
Ne pas décompter d'essai si le serveur part en Timeout

### ISSUE THREAD

**Issue by antoinemichaud** [antoinemichaud/tennisevolution#56]

**Comment by mthuret** [comment]
Tu as le use case ? Car j'ai pas réussi à reproduire, de mon côté si l'un ou l'autre des serveurs est done, ça ne décompte pas de trial.

**Comment by antoinemichaud** [comment]
Quand j'ai ajouté le ticket c'était plutôt parce que je pensais qu'on décomptait les essais, je ne l'ai pas constaté en fait. Je ferme ce ticket.
