### ISSUE TITLE
Champ success incohérent avec le champ error

### ISSUE THREAD

**Issue by antoinemichaud** [antoinemichaud/tennisevolution#58]

**Comment by mthuret** [comment]
Pour moi c'est bon, mais je préfère que tu valides :)

**Comment by antoinemichaud** [comment]
Oui effectivement maintenant c'est cohérent mais en fait il y a toujours un problème. Je ne sais pas encore comment le reproduire mais c'est potentiellement très gênant si ça arrive pendant l'atelier. J'obtiens ça : 
`query to candidate server:  http://172.17.0.1:8080/displayScore?player1Name=player1&player1Score=8&player2Name=player2&player2Score=9
query to ref server:  http://localhost:8083/classic/displayScore?player1Name=player1&player1Score=8&player2Name=player2&player2Score=9
candidate response:  win for player1 reference response: advantage player2`

Mais quand je lance la requête sur le code "participant", j'obtiens pourtant bien "advantage player2".

Les requêtes suivantes, c'est similaire. Je les ajoute à titre d'exemple : 

`query to candidate server:  http://172.17.0.1:8080/displayScore?player1Name=player1&player1Score=1&player2Name=player2&player2Score=1
query to ref server:  http://localhost:8083/classic/displayScore?player1Name=player1&player1Score=1&player2Name=player2&player2Score=1
candidate response:  deuce reference response: fifteen-all
query to candidate server:  http://172.17.0.1:8080/displayScore?player1Name=player1&player1Score=2&player2Name=player2&player2Score=2
query to ref server:  http://localhost:8083/classic/displayScore?player1Name=player1&player1Score=2&player2Name=player2&player2Score=2
candidate response:  deuce reference response: thirty-all
query to candidate server:  http://172.17.0.1:8080/displayScore?player1Name=player1&player1Score=1&player2Name=player2&player2Score=1
query to ref server:  http://localhost:8083/classic/displayScore?player1Name=player1&player1Score=1&player2Name=player2&player2Score=1
candidate response:  deuce reference response: fifteen-all`

Quand c'est dans cet état, je n'obtiens plus que des résultats incohérents dans les autres compare. Pour que ça arrête de planter, il faut que je redémarre le serveur node et ça se met à fonctionner à nouveau.

**Comment by mthuret** [comment]
A retester

**Comment by antoinemichaud** [comment]
Ok, je rejouerai l'atelier en entier ce soir

**Comment by antoinemichaud** [comment]
J'ai également créé une nouvelle instance pour la route avec language. Je clos.
